application: denero-org
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: published/index.html
  upload: published/index.html

- url: /
  static_dir: published
