application: denero-org
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: index.html
  upload: index.html

- url: /meet
  static_files: meet
  upload: meet
  mime_type: text/html

- url: /blog
  static_dir: blog

- url: /content
  static_dir: content

- url: /pages
  static_dir: pages

- url: /theme
  static_dir: theme
